---
Name: calendar-contacts
After:
  - 'framework/*'
  - 'cms/*'
  - 'calendar/*'
  - 'directory/*'
---

# Extensions
Event:
  extensions:
    - CalendarContactsEventExtension

CMDirectoryEntry:
  extensions:
    - CalendarDirectoryEntryExtension

CMDirectory:
  extensions:
    - CalendarDirectoryExtension
